#if !canImport(ObjectiveC)
import XCTest

extension TargetDependencyCheckerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TargetDependencyCheckerTests = [
        ("testDirectDependencyWarning", testDirectDependencyWarning),
        ("testDirectDependencyWarningXcode", testDirectDependencyWarningXcode),
        ("testIgnoreIncludes", testIgnoreIncludes),
        ("testIgnoreIncludesCommaSeparated", testIgnoreIncludesCommaSeparated),
        ("testIndirectDependencyWarning", testIndirectDependencyWarning),
        ("testIndirectDependencyWarningXcode", testIndirectDependencyWarningXcode),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TargetDependencyCheckerTests.__allTests__TargetDependencyCheckerTests),
    ]
}
#endif
